# Generated by Django 3.2.12 on 2022-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220829_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='upload',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
