# Generated by Django 3.2.12 on 2022-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220830_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('Wax', 'Wax'), ('Gippure', 'Gippure'), ('Sari', 'Sari'), ('Tissu', 'Tissu')], max_length=100),
        ),
    ]
