# Generated by Django 3.2.12 on 2022-09-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
    ]
